//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "JoystickView.hh"

namespace Smart {

JoystickView::JoystickView(LinuxJoystickDriverModel *model)
:	AbstractView(model)
{  }

JoystickView::~JoystickView()
{  }

void JoystickView::update()
{
	//FIXME: implement this method
}

LinuxJoystickDriverModel* JoystickView::getModel() const {
	return dynamic_cast<LinuxJoystickDriverModel*>(model);
}

} /* namespace Smart */
